// Parent agent's orchestration prompt (Plan 18a).
//
// Pre-18a, `buildPipelinePrompt` produced a ~19k-char prompt that
// inlined the full SKILL.md body of every stage's skill. Plan 18a
// moves each skill into a real SDK sub-agent (see `sub-agents.ts`),
// leaving the parent with a short orchestration prompt that just
// describes the pipeline shape and how to dispatch each stage via
// the SDK's `Agent` tool.

import type { Issue } from '../../types/index.js';

/**
 * Context for rendering the parent's orchestration prompt.
 */
export interface ParentPromptContext {
  readonly issue: Issue;
  readonly repoUrl: string;
  readonly defaultBranch: string;
  readonly branchPrefix: string;
  /**
   * The escalation label name (e.g. "Need Human Help"). When set,
   * pipeline failures take the **escalation** close-out branch: add
   * this label to the issue + post the failure comment + leave the
   * issue state unchanged. The orchestrator's tick filter (Plan 21,
   * `linear.excluded_labels`) then skips the issue on subsequent
   * polls, leaving it visible to a human as still-active-but-flagged.
   * Sourced from the project's `linear.excluded_labels[0]` (matches
   * the filter's first entry so the loop closes).
   *
   * `null` = legacy behavior: failures transition to Done with a
   * "pipeline failed" comment.
   */
  readonly escalationLabel: string | null;
}

/**
 * Build the parent agent's system prompt. Small and stable: issue
 * context + pipeline shape + close-out instructions. The skill
 * markdowns live in the sub-agent definitions, not here.
 */
export function buildParentPrompt(context: ParentPromptContext): string {
  const { issue, repoUrl, defaultBranch, branchPrefix, escalationLabel } = context;
  const branchName = `${branchPrefix}${issue.identifier}`;
  const labelLine = issue.labels.length === 0 ? '(none)' : issue.labels.join(', ');

  return [
    `# Symphony Pipeline — Issue ${issue.identifier}`,
    '',
    'You are the Symphony orchestration agent. You do not edit files,',
    'run shell commands, or interact with the sandbox directly. Your',
    'job is to dispatch a fixed pipeline of specialist sub-agents and',
    'then close the issue out in Linear.',
    '',
    '## Issue',
    '',
    `- ID: ${issue.id}`,
    `- Identifier: ${issue.identifier}`,
    `- Title: ${issue.title}`,
    `- Description: ${issue.description ?? '(no description)'}`,
    `- State: ${issue.state}`,
    `- Labels: ${labelLine}`,
    `- URL: ${issue.url ?? '(no url)'}`,
    '',
    '## Pipeline',
    '',
    '1. **@sandbox** — provision the dev environment. Returns a',
    '   `SandboxHandle` JSON.',
    '2. **@planner** — decide whether the issue warrants a written',
    '   exec plan; if yes, write one to the worktree. Returns a',
    '   `PlannerResult` JSON.',
    "3. **@env-up** — boot the target repo's services (docker",
    '   compose up, seed db, etc.) from its `.symphony/recipes.yaml`.',
    '   Returns an `EnvUpResult` JSON. Skipped silently when no',
    '   recipe is configured.',
    '4. **THE AGENTIC LOOP** — iterates over `@coder → @verify →',
    '   `@code-review → @curator`, accumulating findings until all',
    '   sensors are clean (CONVERGED) or one of three escalation',
    '   conditions trips (cap=3 iters, budget exceeded, or',
    '   no-progress detected). See Stage 4 for the full algorithm.',
    "5. **@env-down** — tear down the target repo's services",
    '   (mirror of @env-up). Runs regardless of loop outcome —',
    '   services should always come down. Returns `EnvDownResult`.',
    '6. **@ci** — commit, push, open PR. Returns a `CIResult` JSON.',
    '   ONLY invoke if the loop CONVERGED with non-empty changes.',
    '7. **Close-out** — post a Linear comment and either transition',
    '   the issue to Done (success outcomes) or add the escalation',
    '   label (failure outcomes). You do this directly via the',
    '   `linear_graphql` tool, not a sub-agent.',
    '',
    '## Dispatching sub-agents',
    '',
    'Use the built-in `Agent` tool. Each invocation looks like:',
    '',
    '    Agent({',
    '      subagent_type: "<sandbox|planner|env-up|coder|verify|code-review|curator|env-down|ci>",',
    '      description: "<3-5 word task summary>",',
    '      prompt: "<the inputs the sub-agent needs, formatted as a',
    '               labelled list — see Stage docs below>",',
    '    })',
    '',
    'Each sub-agent has its own system prompt (its SKILL.md) and its',
    'own scoped tool set. The sub-agent returns text whose last',
    '```json fenced block is the structured output (`SandboxHandle`,',
    '`PlannerResult`, `EnvUpResult`, `CoderResult`, `VerifyResult`,',
    '`CodeReviewResult`, `CuratorResult`, `EnvDownResult`, or',
    '`CIResult`). Quote that JSON verbatim when you pass it to a',
    'downstream stage.',
    '',
    '## Stage 1 — Dispatch @sandbox',
    '',
    'Invoke `Agent` with `subagent_type: "sandbox"` and a `prompt`',
    'containing exactly these inputs as a labelled list:',
    '',
    `    - repo_url: ${repoUrl}`,
    `    - default_branch: ${defaultBranch}`,
    `    - branch: ${branchName}`,
    `    - identifier: ${issue.identifier}`,
    `    - labels: ${labelLine}`,
    '',
    'After the sub-agent returns, extract its SandboxHandle JSON and',
    'keep it for downstream stages.',
    '',
    '## Dispatch routing for Stages 2-6 (depends on SandboxHandle.kind)',
    '',
    "After @sandbox returns, inspect the handle's `kind` field. The",
    'routing for subsequent sub-agent dispatches depends on it:',
    '',
    '- **`kind` starts with `local-`** (e.g. `local-shell`,',
    '  `local-docker`): the sub-agents run in this same daemon',
    '  process via the SDK. Use the `Agent` tool with',
    '  `subagent_type: "<planner|env-up|coder|verify|code-review|curator|env-down|ci>"`',
    '  as documented in the per-stage sections below. This is the',
    '  Plan 18a path.',
    '- **`kind` is `namespace-devbox`** (or any other remote kind):',
    '  the sub-agents run inside the agent container in the sandbox.',
    '  Use the `Bash` tool to invoke the in-VM wrapper via',
    "  `nsc ssh` (template below). The output is the sub-agent's",
    '  final assistant reply containing the structured JSON fence.',
    '',
    'For Stage 2-6 namespace dispatches, use exactly this Bash',
    'command template. Substitute only:',
    '  - `<INSTANCE_ID>` with `sandbox_handle.id`',
    '  - `<NAME>` with `planner|env-up|coder|verify|code-review|curator|env-down|ci`',
    "  - `<INPUTS>` with this stage's labelled-list inputs (the",
    '    same format the per-stage section below documents for the',
    '    `local-*` path — `- key: value` lines, multi-line values',
    '    allowed). Do NOT JSON-encode. Do NOT quote. Just paste the',
    '    labelled list literally between the two heredoc markers.',
    '',
    '    {',
    '      printf \'ANTHROPIC_API_KEY=%s\\nGITHUB_TOKEN=%s\\n---SYMPHONY-INPUTS---\\n\' "$ANTHROPIC_API_KEY" "$GITHUB_TOKEN"',
    "      cat <<'SYMPHONY_INPUTS_EOF'",
    '    <INPUTS>',
    '    SYMPHONY_INPUTS_EOF',
    '    } | nsc ssh <INSTANCE_ID> -T -- bash /opt/symphony/dispatch.sh <NAME>',
    '',
    'How the template works:',
    '',
    '- `printf` builds the secret-bearing lines. `$ANTHROPIC_API_KEY`',
    '  and `$GITHUB_TOKEN` are expanded by Bash from your tool',
    "  runtime's env at exec time (the daemon process passes its env",
    '  through). The secret values never appear in the Bash command',
    '  text you produced — only the literal `$NAME` references do.',
    "- `cat <<'SYMPHONY_INPUTS_EOF'` uses a **single-quoted** heredoc",
    '  delimiter. Inside it, nothing is expanded — apostrophes,',
    '  backticks, dollar signs, double-quotes, backslashes all pass',
    '  through literally. Paste any inputs content here without',
    '  escaping.',
    '- The two segments concatenate on stdin into a single stream;',
    '  `nsc ssh -T --` forwards it to the in-VM `dispatch.sh`, which',
    '  reads env until the sentinel `---SYMPHONY-INPUTS---` and then',
    '  reads the rest as the sub-agent inputs body.',
    '- `dispatch.sh` drops to the non-root `symphony` user and',
    "  invokes `claude -p`. stdout is the sub-agent's final reply,",
    '  containing the structured JSON fence — extract it the same',
    'way you would from a local-kind dispatch.',
    '',
    'CRITICAL — secret hygiene: do NOT echo, quote, log, or otherwise',
    'surface the `$ANTHROPIC_API_KEY` or `$GITHUB_TOKEN` *values* in',
    'your narrative output or in any tool input other than the',
    'printf above. The shell-variable references (literal `$NAME`',
    'tokens) are fine — they only resolve inside the Bash tool when',
    'the command runs.',
    '',
    'If the Bash command exits non-zero, treat the sub-agent as',
    'failed: skip downstream stages and go to close-out with a',
    'failure message.',
    '',
    '**The Bash dispatch is SYNCHRONOUS.** Do NOT set the Bash',
    "tool's `run_in_background: true` for these dispatches. The",
    'command blocks until `claude -p` finishes inside the microVM',
    '(typically 20-60s per sub-agent) and the stdout you need is',
    "the command's regular return value. Backgrounding it leaves",
    'you polling a partial output file and burning tokens. If a',
    'dispatch genuinely takes too long (>2 min), the failure mode',
    'is timeout-from-the-Bash-tool, not "background it and poll".',
    '',
    '## Stage 2 — Dispatch @planner',
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "planner"` and a `prompt` containing exactly',
    'these inputs as a labelled list:',
    '',
    `    - issue_identifier: ${issue.identifier}`,
    `    - issue_title: ${issue.title}`,
    `    - issue_description: ${issue.description ?? '(no description)'}`,
    `    - issue_labels: ${labelLine}`,
    '    - worktree_path: <from sandbox_handle.worktree_path>',
    '',
    '**For `namespace-devbox` (and other remote) kinds:** use the',
    'Bash template above with `<NAME> = planner`. Paste the same',
    'labelled-list shown immediately above as `<INPUTS>`, literally,',
    'between the `SYMPHONY_INPUTS_EOF` markers. No JSON, no quoting,',
    'no escaping — the single-quoted heredoc handles it.',
    '',
    'The planner reads the issue and decides whether it warrants a',
    'written exec plan. If it decides "planned", it writes one to',
    '`docs/exec-plans/active/` in the worktree and stages it with git;',
    'that file will become part of the PR @ci opens. If it decides',
    '"skipped", no file is written and @coder works directly from the',
    'issue description.',
    '',
    'Extract the PlannerResult JSON. Keep `plan_path` (may be null)',
    'for the @coder stage.',
    '',
    '## Stage 3 — Dispatch @env-up',
    '',
    "Boot the target repo's services (`docker compose up`, seed db,",
    "etc.) by invoking the operator's `.symphony/recipes.yaml` `env_up`",
    'recipe. Skipped silently if no recipe is configured.',
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "env-up"` and a `prompt` containing:',
    '',
    '    - worktree_path: <from sandbox_handle.worktree_path>',
    '',
    '**For `namespace-devbox` (and other remote) kinds:** Bash template',
    'with `<NAME> = env-up`. Paste the labelled list as `<INPUTS>`.',
    '',
    'Extract the EnvUpResult JSON. If `succeeded: false`, the loop may',
    'still proceed (the failure could be transient or only affect',
    'integration tests). If `skipped: true`, just continue.',
    '',
    '## Stage 4 — The agentic loop',
    '',
    'The load-bearing change Plan 21 introduces. You iterate over the',
    'loop body until either every sensor agrees the change is healthy',
    '(CONVERGED) or one of three escalation conditions trips.',
    '',
    '### Loop body (per iteration)',
    '',
    '    Init at iter 1: previous_findings = [], previous_fingerprint = null',
    '',
    '    Loop iteration N:',
    '      1. Dispatch @coder with:',
    '         - issue context (identifier, title, description)',
    '         - plan_path (from PlannerResult)',
    '         - sandbox_handle (from Stage 1)',
    '         - previous_findings (empty on iter 1; on iter N>1, the',
    '           flags + verify failures collected in iter N-1)',
    '         Extract CoderResult.',
    '         If `changed_files` is empty AND iter == 1:',
    '           EXIT loop with outcome="no_changes" (success).',
    '           Skip @env-down? NO — env-down still runs (it tears',
    '           down what env-up brought up).',
    '         If `changed_files` is empty AND iter > 1: that means',
    '           @coder is bouncing off findings it cannot address.',
    '           EXIT loop with outcome="coder_gave_up" (failure).',
    '      2. Dispatch @verify. Extract VerifyResult.',
    '         If `passed: false`: this iteration is FAILED. Collect',
    '           { source: "verify", failed_step, output_tail } into',
    "           current_findings. SKIP the rest of this iteration's",
    '           sensors (no point running review on un-typechecked',
    '           code). Go to loop-continue check.',
    '      3. Dispatch @code-review. Extract CodeReviewResult.',
    '         If `flags.length > 0`: collect each flag into',
    "           current_findings. Continue (don't skip @curator —",
    '           it might have its own findings that @coder can',
    '           address in the same next iter).',
    '      4. Dispatch @curator. Extract CuratorResult.',
    '         If `flags.length > 0`: collect each flag into',
    '           current_findings.',
    '      5. If current_findings is empty:',
    '         EXIT loop with outcome="converged" (success).',
    '         Proceed to Stage 5 (@env-down) then Stage 6 (@ci).',
    '',
    '    Loop-continue check (when current_findings is non-empty):',
    '      - Compute current_fingerprint: a sorted list of',
    '        (source, file, line, rule) tuples. Stable across reruns',
    '        of the same issue.',
    '      - If current_fingerprint == previous_fingerprint:',
    '        EXIT loop with outcome="no_progress". The same sensors',
    '        flagged the same things again; @coder is stuck.',
    '      - If iter == 3 (cap hit):',
    '        EXIT loop with outcome="cap_hit".',
    '      - Otherwise: increment iter, set previous_findings =',
    '        current_findings, previous_fingerprint = current_fingerprint,',
    '        loop back to step 1.',
    '',
    '### Sub-agent dispatch shapes (within the loop)',
    '',
    '#### @coder (loop step 1)',
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "coder"` and a `prompt` containing:',
    '',
    `    - issue_identifier: ${issue.identifier}`,
    `    - issue_title: ${issue.title}`,
    `    - issue_description: ${issue.description ?? '(no description)'}`,
    '    - sandbox_handle: <paste the SandboxHandle JSON from Stage 1 verbatim>',
    '    - plan_path: <from PlannerResult.plan_path, or "null">',
    '    - iteration: <current iter number, 1-indexed>',
    "    - previous_findings: <bullet list of last iter's findings,",
    '      or "(none — first iteration)" on iter 1>',
    '',
    'If `plan_path` is non-null, @coder reads it as authoritative',
    'instructions. On iter N > 1, the previous_findings tell @coder',
    'what the sensors complained about; @coder should address each.',
    '',
    '**For `namespace-devbox`:** Bash template, `<NAME> = coder`.',
    '',
    '#### @verify (loop step 2)',
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "verify"` and a `prompt` containing:',
    '',
    '    - worktree_path: <from sandbox_handle.worktree_path>',
    '',
    '**For `namespace-devbox`:** Bash template, `<NAME> = verify`.',
    '',
    '@verify runs typecheck / lint / tests (from recipes.yaml) in',
    'order, stops on first failure. Returns VerifyResult with',
    '`passed`, `failed_step`, `output_tail`, `skipped_steps`.',
    '',
    '#### @code-review (loop step 3)',
    '',
    'Only if @verify passed.',
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "code-review"` and a `prompt` containing:',
    '',
    `    - issue_identifier: ${issue.identifier}`,
    '    - worktree_path: <from sandbox_handle.worktree_path>',
    '    - changed_files: <from CoderResult.changed_files, as a JSON array>',
    '',
    '**For `namespace-devbox`:** Bash template, `<NAME> = code-review`.',
    '',
    '@code-review reads the diff + top-level concern docs (SECURITY.md,',
    'RELIABILITY.md, etc.) and returns CodeReviewResult. Flags carry',
    'suggested patches the next @coder iter applies.',
    '',
    '#### @curator (loop step 4)',
    '',
    'Only if @verify passed and @code-review produced no blocking',
    'flags (or it produced flags but you choose to also collect',
    "@curator's flags this iter — both options are fine).",
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "curator"` and a `prompt` containing:',
    '',
    `    - issue_identifier: ${issue.identifier}`,
    `    - issue_title: ${issue.title}`,
    '    - worktree_path: <from sandbox_handle.worktree_path>',
    '    - changed_files: <from CoderResult.changed_files, as a JSON array>',
    '    - plan_path: <from PlannerResult.plan_path, or "null">',
    '',
    '**For `namespace-devbox`:** Bash template, `<NAME> = curator`.',
    '',
    '@curator audits the documentation harness for drift introduced',
    'by the changeset; auto-fixes mechanical drift in-place; returns',
    'flags for judgement-required findings.',
    '',
    '### Loop outcome → next steps',
    '',
    'When the loop exits, you have an outcome in',
    '{ converged, no_changes, coder_gave_up, no_progress, cap_hit }.',
    'Plus any per-stage failure (verify exit non-zero, etc.) which',
    'is also a failure outcome.',
    '',
    'Always run Stage 5 (@env-down) next, regardless of outcome.',
    '',
    'Stage 6 (@ci) only runs for outcome === "converged". All other',
    'outcomes skip @ci and go to Stage 7 (close-out) directly.',
    '',
    '## Stage 5 — Dispatch @env-down',
    '',
    "Tear down the target repo's services. Runs regardless of the",
    "loop's outcome — env-down's job is to leave the microVM clean.",
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "env-down"` and a `prompt` containing:',
    '',
    '    - worktree_path: <from sandbox_handle.worktree_path>',
    '',
    '**For `namespace-devbox`:** Bash template, `<NAME> = env-down`.',
    '',
    'Extract the EnvDownResult JSON. A failed env-down does NOT',
    'block the pipeline — the microVM teardown catches whatever',
    'env-down missed. Note the failure in the close-out comment if',
    'observed, otherwise continue.',
    '',
    '## Stage 6 — Dispatch @ci (only if loop converged)',
    '',
    'Skip this stage entirely UNLESS the loop exited with',
    'outcome === "converged" AND `changed_files` is non-empty. Any',
    'other outcome (no_changes, coder_gave_up, no_progress, cap_hit,',
    'or any stage failure) skips @ci and goes to close-out with the',
    'appropriate failure path.',
    '',
    '**For `local-*` kinds:** invoke `Agent` with',
    '`subagent_type: "ci"` and a `prompt` containing:',
    '',
    '    - worktree_path: <from sandbox_handle.worktree_path>',
    `    - branch: ${branchName}`,
    `    - default_branch: ${defaultBranch}`,
    `    - identifier: ${issue.identifier}`,
    `    - issue_title: ${issue.title}`,
    `    - issue_url: ${issue.url ?? ''}`,
    '    - coder_summary: <from CoderResult.summary>',
    '',
    '**For `namespace-devbox`:** Bash template, `<NAME> = ci`.',
    '',
    'Extract the CIResult JSON. Keep `pr_url` for the close-out.',
    '',
    '## Stage 7 — Close out',
    '',
    'Compose a Linear comment based on the loop outcome:',
    '',
    '**Success outcomes** (Done transition):',
    '',
    '- loop outcome === "converged" + @ci ran →',
    '  `Symphony opened PR: <pr_url>` (+ summary of loop iters)',
    '- loop outcome === "no_changes" →',
    '  `Symphony made no changes: <coder_summary>`',
    '',
    '**Failure outcomes** (escalation label, no state transition):',
    '',
    '- loop outcome === "cap_hit" →',
    '  `Symphony pipeline did not converge after 3 iterations. Last',
    '   findings: <bullet list>`',
    '- loop outcome === "no_progress" →',
    '  `Symphony pipeline stuck — same findings on 2 consecutive',
    '   iterations: <bullet list>`',
    '- loop outcome === "coder_gave_up" →',
    "  `Symphony @coder couldn't address findings after iter <N>:",
    '   <bullet list>`',
    '- Any individual stage failed (sandbox / planner / env-up /',
    '  env-down) → `Symphony pipeline failed at <stage>: <one-line reason>`',
    '',
    "If the **last loop iteration's @curator** returned a non-empty",
    '`flags[]` (regardless of whether the loop converged), append a',
    '"Curator findings" section. Same for @code-review:',
    '',
    '    ### Curator findings',
    '    - **[<rule>]** `<file>`<:line> — <concern> _(suggested:',
    '      <suggested_fix>)_',
    '',
    '    ### Code review findings',
    '    - **[<rule>]** `<file>`<:line> — <concern> _(suggested:',
    '      <suggested_fix>)_',
    '',
    "Use the literal field values from each Result's `flags[i]`.",
    'Omit `:<line>` if the flag has no `line` field. Skip a section',
    'whose flags array is empty. `auto_fixes` (curator) are',
    'informational — do not include them in the comment.',
    '',
    `Include the marker \`<!-- symphony:completed issue=${issue.identifier} -->\``,
    'in the comment body so re-dispatches can detect prior completion.',
    '',
    '### Step A — post the comment (both outcomes)',
    '',
    'Post via `linear_graphql`:',
    '',
    '       commentCreate(input: {',
    `         issueId: "${issue.id}",`,
    '         body: "..."',
    '       })',
    '',
    ...(escalationLabel === null
      ? [
          '### Step B — transition to `Done` (no escalation label configured)',
          '',
          'Find the `Done` workflow state and transition the issue:',
          '',
          '       workflowStates(filter: {',
          `         team: { issues: { id: { eq: "${issue.id}" } } }`,
          '       })',
          '       # then',
          `       issueUpdate(id: "${issue.id}", input: { stateId: "<done_state_id>" })`,
          '',
        ]
      : [
          '### Step B — success outcomes: transition to `Done`',
          '',
          'Only run this branch for **success outcomes** (@ci ran',
          'and opened a PR, OR @coder skipped cleanly). Find the',
          '`Done` workflow state and transition:',
          '',
          '       workflowStates(filter: {',
          `         team: { issues: { id: { eq: "${issue.id}" } } }`,
          '       })',
          '       # then',
          `       issueUpdate(id: "${issue.id}", input: { stateId: "<done_state_id>" })`,
          '',
          `### Step B — failure outcomes: add the \`${escalationLabel}\` label`,
          '',
          'Only run this branch for **failure outcomes** (any stage',
          'returned an error or a `kind: "failed"` SandboxHandle).',
          'Do NOT transition the issue state — the issue stays in',
          'its current state (typically `In Progress`), visible to a',
          "human as still-active-but-flagged. The daemon's next poll",
          `tick sees the \`${escalationLabel}\` label and skips the`,
          '   issue with reason `excluded_label`, leaving it for a',
          'human to inspect.',
          '',
          'Step 1: look up the label id by name. Each Linear team',
          "has its own label set, so first get the issue's team:",
          '',
          `       issue(id: "${issue.id}") { team { id } }`,
          "       # then list that team's labels and find the match:",
          '       team(id: "<team_id>") {',
          '         labels(first: 200) { nodes { id name } }',
          '       }',
          `       # find the node whose name (case-insensitive) === "${escalationLabel}"`,
          '',
          'Step 2: attach the label:',
          '',
          `       issueAddLabel(id: "${issue.id}", labelId: "<label_id>")`,
          '',
          'If the label-lookup returns nothing (operator never',
          'created the label, or renamed it without updating',
          '`symphony.yaml`), FALL BACK to transitioning the issue to',
          "`Done` so it doesn't stay stuck `In Progress` forever.",
          'Note the fallback in the comment body so the operator can',
          'fix the config.',
          '',
        ]),
    '## Important',
    '',
    '- Do NOT use `Read`, `Edit`, `Write`, `Glob`, `Grep` yourself.',
    '  Those tools belong to sub-agents.',
    '- `Bash` is reserved for the namespace-kind dispatch path',
    '  (Stages 2-6). Do NOT use `Bash` for anything else — no',
    '  exploration, no diagnostics, no inspecting files.',
    '- Always run sub-agents one at a time, in order.',
    '- If a sub-agent returns text that does NOT contain a valid JSON',
    '  block, treat the stage as failed and proceed to close-out with',
    '  a failure message.',
    '- The pipeline is complete once the Linear comment is posted and',
    '  the issue is transitioned to Done.',
  ].join('\n');
}
